import { prisma } from "@/lib/prisma";

export const PosTransactionRepository = {
  async cancelTransaction(transactionId: string) {
    return await prisma.$transaction(async (tx) => {
      const transaction = await tx.transaction.findUnique({
        where: { id: transactionId },
        include: {
          items: { include: { serviceSessions: true } },
          voucherRedemptions: true
        }
      });

      if (!transaction) throw new Error("Transaksi tidak ditemukan.");
      if (transaction.status === "VOIDED" || transaction.status === "CANCELLED") {
        throw new Error("Transaksi sudah dibatalkan.");
      }

      // 1. Mark transaction as VOIDED
      await tx.transaction.update({
        where: { id: transaction.id },
        data: { status: "VOIDED" }
      });

      // 2. Mark related service sessions as CANCELLED
      for (const item of transaction.items) {
        for (const session of item.serviceSessions) {
          await tx.serviceSession.update({
            where: { id: session.id },
            data: { status: "CANCELLED" }
          });
        }
      }

      // 3. Restore any vouchers generated by this transaction
      const generatedVouchers = await tx.customerVoucher.findMany({
        where: { sourceTransactionId: transaction.id }
      });

      for (const voucher of generatedVouchers) {
        const redemptions = await tx.voucherRedemption.count({ where: { customerVoucherId: voucher.id } });
        if (redemptions > 0) throw new Error("Tidak dapat membatalkan transaksi karena voucher yang dibeli sudah digunakan.");

        await tx.customerVoucher.update({
          where: { id: voucher.id },
          data: { status: "VOID" }
        });
      }

      // 4. Reverse any vouchers redeemed BY this transaction
      for (const redemption of transaction.voucherRedemptions) {
        const voucher = await tx.customerVoucher.findUnique({ where: { id: redemption.customerVoucherId } });
        if (voucher) {
          const newVisitCount = voucher.remainingVisitCount != null ? voucher.remainingVisitCount + (redemption.redeemedVisitCount || 0) : null;
          const newCreditAmount = voucher.remainingCreditAmount != null ? Number(voucher.remainingCreditAmount) + Number(redemption.redeemedAmount || 0) : null;

          await tx.customerVoucher.update({
            where: { id: voucher.id },
            data: {
              remainingVisitCount: newVisitCount,
              remainingCreditAmount: newCreditAmount,
              status: "ACTIVE"
            }
          });
        }
      }

      return { success: true };
    });
  }
};
